##
##  HUDS -- Head-Up-Display Server (HUDS)
##  Copyright (c) 2020 Dr. Ralf S. Engelschall <rse@engelschall.com>
##
##  Permission is hereby granted, free of charge, to any person obtaining
##  a copy of this software and associated documentation files (the
##  "Software"), to deal in the Software without restriction, including
##  without limitation the rights to use, copy, modify, merge, publish,
##  distribute, sublicense, and/or sell copies of the Software, and to
##  permit persons to whom the Software is furnished to do so, subject to
##  the following conditions:
##
##  The above copyright notice and this permission notice shall be included
##  in all copies or substantial portions of the Software.
##
##  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
##  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
##  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
##  IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
##  CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
##  TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
##  SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
##

title:
    opacity:               0.80
    background:            "#336699"
    iconname:              graduation-cap
    iconcolor:             "#77aadd"
    nametext:              Dr. Ralf S. Engelschall
    namecolor:             "#e0f0ff"
    titletext:             Grundlagen der IT-Architektur
    titlecolor:            "#ffffff"

attendance:
    opacity:               0.80
    background:            "#336699"
    iconcolor:             "#77aadd"
    textcolor:             "#e0f0ff"

feedback:
    opacity:               0.80
    background:            "#333333"
    iconcolor:             "#d08840"
    badgecolor:            "#666666"
    textcolor:             "#ffffff"

feeling:
    opacity:               0.80
    background:            "#333333"
    textcolor:             "#c0c0c0"
    q1color:               "#999999"
    q2color:               "#c0c0c0"
    q3color:               "#c0c0c0"
    q4color:               "#999999"
    c1color:               "#a05810"
    c2color:               "#b06820"
    c3color:               "#c0c0c0"
    c4color:               "#b06820"
    c5color:               "#a05810"
    m1color:               "#a05810"
    m2color:               "#b06820"
    m3color:               "#c0c0c0"
    m4color:               "#336699"
    m5color:               "#225588"

closure:
    opacity:               0.75
    background:            "#000000"
    beginiconname:         "play-circle"
    beginiconcolor:        "#b06820"
    beginhinttext:         "The training will start soon.<br/>Please be patient!"
    beginhintcolor:        "#ffffff"
    pauseiconname:         "pause-circle"
    pauseiconcolor:        "#336699"
    pausehinttext:         "The training is paused.<br/>Please be patient!"
    pausehintcolor:        "#ffffff"
    endiconname:           "stop-circle"
    endiconcolor:          "#b06820"
    endhinttext:           "The training already has ended.<br/>Thanks for your attention!"
    endhintcolor:          "#ffffff"

popup:
    opacity:               0.80
    questionbackground:    "#336699"
    questiontitlecolor:    "#e0f0ff"
    questionmessagecolor:  "#ffffff"
    objectionbackground:   "#333333"
    objectiontitlecolor:   "#e0e0e0"
    objectionmessagecolor: "#ffffff"
    commentbackground:     "#f0f0f0"
    commenttitlecolor:     "#333333"
    commentmessagecolor:   "#000000"

timer:
    opacity:               0.80
    background1:           "#555555"
    background2:           "#f0f0f0"
    ticks:                 "#333333"
    digits:                "#666666"
    pointer1:              "#000000"
    pointer2:              "#222222"
    pointer3:              "#cc3333"
    segment1:              "#b06820"
    segment2:              "#f4dbc2"
    segment3:              "#2068b0"
    segment4:              "#c2dbf4"

progress:
    opacity:               0.80
    slots:                 16
    donecolorbg:           "#6699cc"
    donecolorfg:           "#f0f0ff"
    currcolorbg:           "#336699"
    currcolorfg:           "#ffffff"
    todocolorbg:           "#f0f0f0"
    todocolorfg:           "#999999"

votes:
    opacity:               0.80
    maxnamecolorbg:        "#336699"
    maxnamecolorfg:        "#ffffff"
    stdnamecolorbg:        "#6699cc"
    stdnamecolorfg:        "#ffffff"
    maxvotecolorbg:        "#ffffff"
    maxvotecolorfg:        "#666666"
    stdvotecolorbg:        "#f0f0f0"
    stdvotecolorfg:        "#999999"
    hint:                  "Please give your vote to the trainer by sending a message with<br/><kbd>#</kbd> <kbd><i>Your-Vote-Word</i></kbd> <kbd>RETURN</kbd>"

banner:
    opacity:               0.80
    background:            "#f0f0f0"
    banner:
        -   name:          pause
            key:           p
            iconname:      pause-circle
            iconcolor:     "#336699"
            titletext:     PAUSE
            titlecolor:    "#000000"
        -   name:          rant
            key:           r
            iconname:      radiation-alt
            iconcolor:     "#bb0000"
            titletext:     RANT
            titlecolor:    "#000000"
        -   name:          praise
            key:           x
            iconname:      award
            iconcolor:     "#336699"
            titletext:     PRAISE
            titlecolor:    "#000000"
        -   name:          qna
            key:           q
            iconname:      comments
            iconcolor:     "#b06820"
            titletext:     "Q&A"
            titlecolor:    "#000000"

logo:
    opacity:               0.60
    svg: |
        <svg id="msg-logo" data-name="msg-logo 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 226.3 70.78">
            <defs><style>.cls-1{fill:#fff;}</style></defs>
            <path class="cls-1" d="M3.88,47.39A11.78,11.78,0,1,1,15.66,59.17,11.78,11.78,0,0,1,3.88,47.39" transform="translate(-3.88 -4.67)"/>
            <path class="cls-1" d="M35,4.67V58.82h9.88V12.91H67.55V58.82h9.91V12.91H92.51c5.09,0,8.68,3.05,8.68,9.67V58.82h9.89v-39c0-7.37-3.81-15.17-13.59-15.17H35" transform="translate(-3.88 -4.67)"/>
            <path class="cls-1" d="M130.87,4.67c-10.67,0-13.91,7.09-13.91,15,0,8.48,3.53,15.62,13.23,15.62h23.52c7.2,0,7.2,5.54,7.2,8.06,0,2.35,0,7.19-7,7.19h-36v8.25H158c10,0,12.88-5.88,12.88-15.36,0-11.3-3.69-16.37-12.24-16.37h-25.4c-6.41,0-6.41-4.33-6.41-7.22,0-2.25.64-7,7.51-7h34.69V4.67H130.87" transform="translate(-3.88 -4.67)"/>
            <path class="cls-1" d="M230.17,4.67v59c0,7.72-3,11.81-12.16,11.81H183.94V66.79h30.91c4.69,0,5.47-1.79,5.48-5.87,0-.44,0-2.1,0-2.1H196.61c-9.35,0-12.4-1.49-14.24-2.8-2.73-2.3-5.4-5-5.4-14.61V21.86c.05-9.08,2.47-11.75,5.11-13.85,2.41-1.93,5.69-3.34,14.51-3.34h33.58m-9.85,8.24s-19.7,0-20.3,0c-10.14-.24-12.6,2.13-12.94,8.78,0,.74,0,2.46,0,9.66,0,8.49,0,11.41,0,11.74.16,7.94,6.38,7.51,12.51,7.48h20.73Z" transform="translate(-3.88 -4.67)"/>
        </svg>

latency:
    opacity:               0.80
    background:            "#336699"
    foreground:            "#ffffff"
    iconcolor:             "#77aadd"

agenda:
    opacity:               0.90
    donecolorbg:           "#6699cc"
    donecolorfg:           "#f0f0ff"
    currcolorbg:           "#336699"
    currcolorfg:           "#ffffff"
    todocolorbg:           "#f0f0f0"
    todocolorfg:           "#999999"
    slots:
        -   Lorem Ipsum 1
        -   Lorem Ipsum 2
        -   Lorem Ipsum 3
        -   Lorem Ipsum 4
        -   Lorem Ipsum 5
        -   Lorem Ipsum 6
        -   Lorem Ipsum 7
        -   Lorem Ipsum 8
        -   Lorem Ipsum 9
        -   Lorem Ipsum 10
        -   Lorem Ipsum 11
        -   Lorem Ipsum 12
        -   Lorem Ipsum 13
        -   Lorem Ipsum 14
        -   Lorem Ipsum 15
        -   Lorem Ipsum 16

